### ISSUE TITLE
Support for path with spaces

### ISSUE THREAD

**Issue by PrzemyslawKlys** [tobysmith568/Run-in-Powershell#3]
I've been a happy user of your extension. It works great and adds on top of native PowerShell Preview extension and helps me greatly. 

However, it seems to have a problem with the path contains spaces. 

![image](https://user-images.githubusercontent.com/15063294/90330998-afceea00-dfb1-11ea-8f03-3cb267cf214f.png)

Thank you

**Comment by tobysmith568** [comment]
Hey @PrzemyslawKlys , I'm happy to hear you're enjoying this extension :)

This was surprising to me because I thought I already supported spaces in paths. I did some digging and it looks like there was a bug and it in fact only supported exactly 1 space in paths. I believe I've fixed this in commit https://github.com/tobysmith568/Run-in-Powershell/commit/5f5a0fadf100b91c4f676d130decd73a9183bed2 .

I've released a new version in the VS Code Marketplace. Could you please open VS Code, install/update to v1.1.0 and see if that's fixed it for you?

Thanks, Toby.

**Comment by PrzemyslawKlys** [comment]
Thank you. Works correctly now. Really appreciate it. It allows me to build my PowerShell modules without stopping work in VSCode! There is a bug in PowerShell extension that when you execute PSScriptAnalyzer within the script it somehow interacts with extension and crashes. 

Would you be interested in some feature requests? I was planning to write my own extension until I found yours, but I miss one thing from it:
- I would like to have the ability to define actions under new buttons, unlimited number of them (so I could define 1 to 10 actions doing different bits)

The reason I'm asking is that I manage a large set of PowerShell modules (50 or so). I wrote some tools around it like build my module but I frequently change 1-3-5 settings in a script before I execute it. 
- Build module but do not release
- Build module including documentation but do not release
- Rebuild PSD1 file only
- Publish

![image](https://user-images.githubusercontent.com/15063294/90339806-b0887000-dff3-11ea-8917-0c15429bdb52.png)

Would it be possible to define button (s) so that for each project it's defined to execute a different files with different arguments? So instead of looking for a file in Explorer, opening it up in code I could just "define" the button for each of those 4 actions and press it. Maybe a confirmation popup would be shown (with text that I could define)... 

I know, I know - it may not be what the extension is supposed to do. It will save me having to develop something of my own - ultimately I will have to learn it anyways - but maybe not yet :-)
